### ISSUE TITLE
GoogleTranslate stops working after some time.

### ISSUE THREAD

**Issue by iamprusty** [Noisyfox/ACT.FFXIVTranslate#7]
Plugin Ver: 1.2.0.92

ACT Version: 3.3.3 R258

Logs: 
```
[2:03:17 PM] (UnknownError)ACT.FFXIVTranslate.translate.TranslateException: Exception of type 'ACT.FFXIVTranslate.translate.TranslateException' was thrown. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 503 (Service Unavailable).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at ACT.FFXIVTranslate.translate.google_unofficial.GoogleTranslateProvider.Translate(List 1 chattingLines)
   --- End of inner exception stack trace ---
   at ACT.FFXIVTranslate.translate.google_unofficial.GoogleTranslateProvider.Translate(List 1 chattingLines)
   at ACT.FFXIVTranslate.translate.TranslateService.TranslateThread.DoWork(TranslateContext context)
```

Google translate (JP to EN) using a paid API appears to stop working after some time. Yandex Translate has no issue.

**Comment by Lemagex** [comment]
I've always assumed this was due to flooding with too many translate requests, this goes away if I disable unnecessary channels that are usually flooded with chat messages and rely more on the Clipboard feature to translate messages one by one.

**Comment by iamprusty** [comment]
That could be it. It's never been an issue until I started getting in to Eureka. All the ノspam in /shout could be what's causing it.

I've recently switched to Microsoft Translate using a pay-as-you-go API and it's working a treat. It's just a shame that Googles Translate is much more accurate.

**Comment by Noisyfox** [comment]
Well the google API I used here is an "unofficial" one so it could have unexpected limitations and could stop working at any time.
I could add a channel-based filter however.
